### ISSUE TITLE
Logo and college name not clearly visible - UI Fix

### ISSUE THREAD

**Issue by Suhaani07** [gdsc-abesit/GDSC-ABESIT#92]
<img width="1056" alt="image" src="https://github.com/gdsc-abesit/GDSC-ABESIT/assets/98284331/a3d0adec-7aa3-4309-b4cc-dea704f1ba1e">
The logo and college name is not clearly visible since the college name is written below the logo. Kindly allow me to fix the issue under Hacktoberfest 2023. I'll be writing the college name beside the logo so that both are visible

**Comment by Ishaan2053** [comment]
Sure! you can start working on this. Just a few pointers though: -

- Use the abbreviation 'ABESIT' alongside GDSC's logo instead of the full name as we already have it in the Hero section.
- Make the text a separate entity that can be hidden on smaller screens (say, smartphones). Something like `className="hidden md:text-md"` should do the trick.

I'll assign you to this issue under Hacktoberfest.
